Add Exit Code Pass Through
chevdor/srtool-cli pull request #27
Opened 2023-05-08 20:01 UTC by wilwade

Closes:  #26

A simple pass-through of the resulting exit code from the command.

Easy code testing? Swap out the command with something like `"false"` and then:

```
cargo run -- build --package=polkadot-runtime ../polkadot; echo $?
```

Before that would return `0` now it will return `1`.

Slightly harder testing is to have a build that will fail and test that without changing the code.

2023-05-08 20:01 UTC, wilwade commented on cli/src/main.rs
> +			_ => std::process::exit(1),
This is a bit hacky, but it is cleaner than the other ways I found and pulls in less stuff.

2023-05-09 09:39 UTC, chevdor requested changes
Thanks for the PR, just one small fix.

2023-05-09 09:39 UTC, chevdor commented on cli/src/main.rs
> +	std::process::exit(status.code().unwrap_or_else(|| 1));
or simply: 
```
std::process::exit(status.code().unwrap_or(1));
```

2023-05-09 18:05 UTC, chevdor approved these changes

2023-05-17 08:48 UTC, merged